frontend_project_list:
    path: /
    controller: App\Controller\FrontEnd\DefaultController::projectAction
    methods: GET

frontend_product_list:
    path: /project/{projectId}
    controller: App\Controller\FrontEnd\DefaultController::productListAction
    methods: GET

api_project_list:
    path: /api/project/list
    controller: App\Controller\Api\ProjectController::listAction
    methods: GET

api_product_list:
    path: /api/project/{projectId}/product/list
    controller: App\Controller\Api\ProductController::listAction
    methods: GET

api_product_change_status:
    path: /api/project/{projectId}/product/{productId}/status_change/{status}
    controller: App\Controller\Api\ProductController::changeStatusAction
    methods: POST

api_product_approve:
    path: /api/project/{projectId}/product/{productId}/approve
    controller: App\Controller\Api\ProductController::approveAction
    methods: POST

api_param_variants_list:
    path: /api/param_varians/list
    controller: App\Controller\Api\VariantsController::listAction
    methods: GET
